language: rust
rust:
  - stable
  - beta
  - nightly
install: rustup target add thumbv7em-none-eabihf
script:
  - cargo build --verbose --all --target=thumbv7em-none-eabihf
  - cargo test --verbose --all
